import { requireUser, sql } from '../db.js';
import { setStar, performRename, performMove, performDelete, performDownload, performCreateFolder, syncStorageAccount } from '../providers/storage.js';
import { sanitizeFileName, normalizeVirtualPath } from '../utils/fileNames.js';
import { startSaga, updateSaga, completeSaga, failSaga } from '../utils/sagas.js';
import { resolveFolderDestination, resolveFolderPath } from '../storage/folderRefs.js';

// Virtual folders are becoming the single registry for folders (P1). Until the
// migration completes, search/starred must surface BOTH representations without
// duplicates: physical rows win, unmatched virtual folders are appended.
async function listVirtualFolderRows(db, userId, { namePattern = null, starredOnly = false }) {
  return await db`
    SELECT vf.id, vf.user_id, vf.parent_path AS virtual_path, vf.name AS file_name,
           TRUE AS is_folder, vf.is_starred AS is_starred, 0::BIGINT AS size,
           'application/vnd.google-apps.folder' AS mime_type,
           vfm.cloud_account_id, vfm.remote_file_id, vfm.remote_parent_id,
           NULL::TIMESTAMPTZ AS remote_created_time, NULL::TIMESTAMPTZ AS remote_modified_time,
           ca.provider, ca.email
    FROM virtual_folders vf
    LEFT JOIN LATERAL (
      SELECT vfm.cloud_account_id, vfm.remote_file_id, vfm.remote_parent_id
      FROM virtual_folder_materializations vfm
      JOIN cloud_accounts ca2 ON ca2.id=vfm.cloud_account_id AND ca2.user_id=vfm.user_id
      WHERE vfm.virtual_folder_id=vf.id AND vfm.user_id=vf.user_id AND vfm.status='active' AND ca2.status='active'
      ORDER BY ca2.created_at ASC, vfm.id ASC LIMIT 1
    ) vfm ON TRUE
    LEFT JOIN cloud_accounts ca ON ca.id=vfm.cloud_account_id AND ca.user_id=vf.user_id
    WHERE vf.user_id=${userId}
      AND (${starredOnly}::boolean = FALSE OR vf.is_starred = TRUE)
      AND (${namePattern}::text IS NULL OR vf.name ILIKE ${namePattern})
    ORDER BY vf.name ASC`;
}

function mergePhysicalThenVirtual(physicalRows, virtualRows, comparator) {
  const seen = new Set(physicalRows.map((row) => `true:${String(row.file_name).toLowerCase()}`));
  const merged = [...physicalRows];
  for (const row of virtualRows) {
    const key = `true:${String(row.file_name).toLowerCase()}`;
    if (!seen.has(key)) { seen.add(key); merged.push(row); }
  }
  return merged.sort(comparator);
}

function normalizePath(input = '/') { return normalizeVirtualPath(input); }
function display(row) { const { encrypted_credentials: _encryptedCredentials, account_status: _accountStatus, ...safeRow } = row || {}; return { ...safeRow, is_folder:Boolean(safeRow.is_folder), is_starred:Boolean(safeRow.is_starred), size:Number(safeRow.size||0), createdTime:safeRow.remote_created_time||null, modifiedTime:safeRow.remote_modified_time||null, capabilities:{starred:safeRow.provider==='google_drive',rename:true,delete:true} }; }
function errorResponse(c, error, fallback='Request failed', code='REQUEST_FAILED') {
  if (error instanceof Response) return error;
  try { console.error('[route-error] files', JSON.stringify({ message: String(error?.message || error).slice(0, 300), code: error?.code || null, status: Number(error?.status) || null })); } catch {}
  const requestedStatus = Number(error?.status);
  const status = [400,404,409,413].includes(requestedStatus) ? requestedStatus : 500;
  return c.json({ error: fallback, code: error?.code || code }, status);
}
async function getFile(c,fileId){const user=await requireUser(c);const db=sql(c.env);const rows=await db`SELECT fm.*,ca.provider,ca.email,ca.encrypted_credentials,ca.total_space,ca.used_space,ca.status AS account_status FROM file_metadata fm JOIN cloud_accounts ca ON ca.id=fm.cloud_account_id WHERE fm.user_id=${user.id} AND fm.id=${fileId} LIMIT 1`;return{user,row:rows[0]||null};}
async function getAccount(c,accountId){const user=await requireUser(c);const db=sql(c.env);const rows=await db`SELECT id,user_id,email,provider,encrypted_credentials,total_space,used_space,status FROM cloud_accounts WHERE id=${accountId} AND user_id=${user.id} LIMIT 1`;return rows[0]||null;}
async function assertActive(row){if(!row)throw Object.assign(new Error('File not found'),{status:404,code:'FILE_NOT_FOUND'});if(row.account_status!=='active')throw Object.assign(new Error('The file account is no longer connected'),{status:409,code:'ACCOUNT_INACTIVE'});}
const SAFE_INLINE_MIME_TYPES=new Set(['image/avif','image/bmp','image/gif','image/jpeg','image/png','image/webp','audio/mpeg','audio/ogg','audio/wav','video/mp4','video/mpeg','video/ogg','video/webm','application/pdf','text/plain']);
const EXTENSION_MIME_TYPES={avif:'image/avif',bmp:'image/bmp',gif:'image/gif',jpeg:'image/jpeg',jpg:'image/jpeg',png:'image/png',webp:'image/webp',mp3:'audio/mpeg',ogg:'audio/ogg',wav:'audio/wav',mp4:'video/mp4',mpeg:'video/mpeg',mpg:'video/mpeg',webm:'video/webm',pdf:'application/pdf',txt:'text/plain'};
function inferMimeType(fileName,currentMime){const mime=String(currentMime||'').toLowerCase();if(SAFE_INLINE_MIME_TYPES.has(mime))return mime;const extension=String(fileName||'').toLowerCase().split('.').pop()||'';return EXTENSION_MIME_TYPES[extension]||mime||'application/octet-stream';}
function safeDownloadFilename(value){return sanitizeFileName(value,{fallback:'download',maxLength:180}).replaceAll('"','')||'download';}
function isProviderAlreadyDeleted(error){const message=String(error?.message||'');return Number(error?.status)===404||/file not found/i.test(message);}
async function deleteRemoteTolerant(env,account,row){try{await performDelete(env,account,row);}catch(error){if(!isProviderAlreadyDeleted(error))throw error;}}
async function purgeVirtualFolderRows(db,userId,row){if(!row.is_folder)return;const parentPath=normalizePath(row.virtual_path||'/');const prefix=normalizePath(`${parentPath}${row.file_name}/`);try{const folders=await db`SELECT id FROM virtual_folders WHERE user_id=${userId} AND ((parent_path=${parentPath} AND name=${row.file_name}) OR left(path,char_length(${prefix}))=${prefix})`;for(const folder of folders){await db`DELETE FROM virtual_folder_materializations WHERE user_id=${userId} AND virtual_folder_id=${folder.id}`;}await db`DELETE FROM virtual_folders WHERE user_id=${userId} AND ((parent_path=${parentPath} AND name=${row.file_name}) OR left(path,char_length(${prefix}))=${prefix})`;}catch(cleanupError){console.error('[files] virtual folder cleanup failed:',cleanupError);}try{await db`DELETE FROM virtual_folder_materializations WHERE user_id=${userId} AND cloud_account_id=${row.cloud_account_id} AND remote_file_id=${String(row.remote_file_id||'')}`;}catch(orphanCleanupError){console.error('[files] orphan materialization cleanup failed:',orphanCleanupError);}}

export async function filesRoutes(app){
  app.get('/api/files',async(c)=>{try{const user=await requireUser(c);const db=sql(c.env);const search=String(c.req.query('search')||'').trim();const path=normalizePath(c.req.query('path')||'/');const limit=Math.max(1,Math.min(Number(c.req.query('limit')||100),200));let rows;if(search){rows=await db`SELECT fm.*,ca.provider,ca.email FROM file_metadata fm JOIN cloud_accounts ca ON ca.id=fm.cloud_account_id WHERE fm.user_id=${user.id} AND ca.status='active' AND fm.file_name ILIKE ${`%${search}%`} ORDER BY fm.is_folder DESC,COALESCE(fm.remote_modified_time,fm.created_at) DESC,fm.file_name ASC LIMIT ${limit}`;const virtualMatches=await listVirtualFolderRows(db,user.id,{namePattern:search});rows=mergePhysicalThenVirtual(rows,virtualMatches,(a,b)=>{if(Boolean(a.is_folder)!==Boolean(b.is_folder))return a.is_folder?-1:1;return String(a.file_name).localeCompare(String(b.file_name));}).slice(0,limit);}else if(c.req.query('starred')==='1'){rows=await db`SELECT fm.*,ca.provider,ca.email FROM file_metadata fm JOIN cloud_accounts ca ON ca.id=fm.cloud_account_id WHERE fm.user_id=${user.id} AND fm.is_starred=TRUE AND ca.status='active' ORDER BY COALESCE(fm.remote_modified_time,fm.remote_created_time) DESC,fm.file_name ASC`;const starredVirtual=await listVirtualFolderRows(db,user.id,{starredOnly:true});const starredTsKey=(row)=>{const value=row.remote_modified_time||row.remote_created_time;const parsed=value?new Date(value).getTime():0;return Number.isFinite(parsed)?parsed:0;};rows=mergePhysicalThenVirtual(rows,starredVirtual,(a,b)=>starredTsKey(b)-starredTsKey(a)||String(a.file_name).localeCompare(String(b.file_name)));}else if(c.req.query('recent')==='1')rows=await db`SELECT fm.*,ca.provider,ca.email FROM file_metadata fm JOIN cloud_accounts ca ON ca.id=fm.cloud_account_id WHERE fm.user_id=${user.id} AND fm.is_folder=FALSE AND ca.status='active' ORDER BY COALESCE(fm.remote_modified_time,fm.remote_created_time) DESC,fm.file_name ASC LIMIT ${limit}`;else rows=await db`SELECT fm.*,ca.provider,ca.email FROM file_metadata fm JOIN cloud_accounts ca ON ca.id=fm.cloud_account_id WHERE fm.user_id=${user.id} AND fm.virtual_path=${path} AND ca.status='active' ORDER BY fm.is_folder DESC,fm.file_name ASC`;return c.json({data:rows.map(display)});}catch(error){return errorResponse(c,error);}});
  app.get('/api/files/:id',async(c)=>{try{const result=await getFile(c,c.req.param('id'));if(!result.row)return c.json({error:'File not found',code:'FILE_NOT_FOUND'},404);return c.json({data:display(result.row)});}catch(error){return errorResponse(c,error);}});
  app.patch('/api/files/:id/star',async(c)=>{try{const result=await getFile(c,c.req.param('id'));if(!result.row){const dbv=sql(c.env);const vf=(await dbv`SELECT id FROM virtual_folders WHERE id=${c.req.param('id')} AND user_id=${result.user.id} LIMIT 1`)[0];if(!vf)return c.json({error:'File not found',code:'FILE_NOT_FOUND'},404);const desired=Boolean(((await c.req.json().catch(()=>({}))).is_starred)??true);await dbv`UPDATE virtual_folders SET is_starred=${desired},updated_at=NOW() WHERE id=${vf.id}`;return c.json({data:{success:true,is_starred:desired,provider_sync:false}});}await assertActive(result.row);const isStarred=Boolean((await c.req.json()).is_starred??true);const account=await getAccount(c,result.row.cloud_account_id);await setStar(c.env,account,result.row,isStarred);await sql(c.env)`UPDATE file_metadata SET is_starred=${isStarred},updated_at=NOW() WHERE id=${result.row.id} AND user_id=${result.user.id}`;return c.json({data:{success:true,is_starred:isStarred,provider_sync:true}});}catch(error){return errorResponse(c,error);}});
  app.patch('/api/files/:id/rename',async(c)=>{let sagaId=null;let remoteSucceeded=false;try{const result=await getFile(c,c.req.param('id'));await assertActive(result.row);const name=sanitizeFileName(String((await c.req.json()).name||''),{fallback:''});if(!name)return c.json({error:'New name is required',code:'INVALID_NAME'},400);const account=await getAccount(c,result.row.cloud_account_id);sagaId=await startSaga(c.env,{userId:result.user.id,accountId:result.row.cloud_account_id,fileId:result.row.id,operation:'rename',payload:{oldName:result.row.file_name,newName:name}});await performRename(c.env,account,result.row,name);remoteSucceeded=true;await updateSaga(c.env,sagaId,'remote_succeeded',{newName:name});await sql(c.env)`UPDATE file_metadata SET file_name=${name},updated_at=NOW() WHERE id=${result.row.id} AND user_id=${result.user.id}`;await completeSaga(c.env,sagaId);return c.json({data:{success:true}});}catch(error){if(sagaId){try{await failSaga(c.env,sagaId,error,remoteSucceeded);}catch(sagaError){console.error('[files] rename saga update failed:',sagaError);}}return errorResponse(c,error,'Rename failed','RENAME_FAILED');}});

  app.post('/api/files/:id/move',async(c)=>{let sagaId=null;let remoteSucceeded=false;try{
      const source=await getFile(c,c.req.param('id'));await assertActive(source.row);const body=await c.req.json();const destinationId=String(body.destination_folder_id||body.destinationFolderId||body.targetFolderId||'').trim();const requestedPath=body.virtual_path||body.virtualPath||null;const db=sql(c.env);
      let destination=null;
      if(destinationId){const rows=await db`SELECT fm.*,ca.provider,ca.email,ca.status AS account_status FROM file_metadata fm JOIN cloud_accounts ca ON ca.id=fm.cloud_account_id WHERE fm.user_id=${source.user.id} AND fm.id=${destinationId} LIMIT 1`;destination=rows[0]||null;if(!destination){const vfDest=await resolveFolderDestination(db,source.user.id,destinationId,source.row.cloud_account_id);if(vfDest&&vfDest.kind==='vf')destination={is_folder:true,virtual_path:vfDest.parentPath,file_name:vfDest.name,cloud_account_id:vfDest.cloudAccountId,remote_file_id:vfDest.remoteParentId,id:vfDest.id};else return c.json({error:'Destination folder not found',code:'DESTINATION_NOT_FOUND'},404);}}
      else if(requestedPath){const destinationPath=normalizePath(requestedPath);if(destinationPath!=='/'){const trimmed=destinationPath.replace(/^\/+|\/+$/g,'');const parts=trimmed.split('/');const folderName=parts.pop();const parentPath=parts.length?`/${parts.join('/')}/`:'/';const rows=await db`SELECT fm.*,ca.provider,ca.email,ca.status AS account_status FROM file_metadata fm JOIN cloud_accounts ca ON ca.id=fm.cloud_account_id WHERE fm.user_id=${source.user.id} AND fm.cloud_account_id=${source.row.cloud_account_id} AND fm.is_folder=TRUE AND fm.virtual_path=${parentPath} AND fm.file_name=${folderName} LIMIT 1`;destination=rows[0]||null;if(!destination){const pathDest=await resolveFolderPath(db,source.user.id,destinationPath);if(pathDest&&pathDest.kind==='vf'){const vfmPreferred=pathDest.materialization&&(pathDest.materialization.cloud_account_id===source.row.cloud_account_id?pathDest.materialization:null)||pathDest.materialization;destination={is_folder:true,virtual_path:pathDest.parentPath,file_name:pathDest.name,cloud_account_id:(vfmPreferred&&vfmPreferred.cloud_account_id)||pathDest.cloudAccountId,remote_file_id:(vfmPreferred&&vfmPreferred.remote_file_id)||pathDest.remoteParentId,id:pathDest.id};}}}}
      if(requestedPath===null&&!destinationId)return c.json({error:'Destination folder is required',code:'DESTINATION_REQUIRED'},400);
      if(requestedPath&&normalizePath(requestedPath)==='/'){destination=null;}
      if(requestedPath!==null&&!destinationId&&!destination&&normalizePath(requestedPath)!=='/')return c.json({error:'Destination folder not found',code:'DESTINATION_NOT_FOUND'},404);
      if(destination){if(destination.account_status!=='active')return c.json({error:'Destination account is not active',code:'DESTINATION_ACCOUNT_INACTIVE'},409);if(!destination.is_folder)return c.json({error:'Destination must be a folder',code:'DESTINATION_NOT_FOLDER'},400);if(destination.cloud_account_id!==source.row.cloud_account_id)return c.json({error:'Cross-account move is not supported',code:'CROSS_ACCOUNT_MOVE'},409);if(destination.id===source.row.id)return c.json({error:'A file or folder cannot be moved into itself',code:'INVALID_MOVE'},400);}
      const destinationVirtualPath=destination?normalizePath(`${destination.virtual_path||'/'}${destination.file_name}`):'/';
      if(source.row.is_folder){const sourceFolderPrefix=normalizePath(`${source.row.virtual_path||'/'}${source.row.file_name}`);if(destinationVirtualPath===sourceFolderPrefix||destinationVirtualPath.startsWith(sourceFolderPrefix))return c.json({error:'A folder cannot be moved into itself or one of its descendants',code:'INVALID_MOVE'},400);}
      const account=await getAccount(c,source.row.cloud_account_id);sagaId=await startSaga(c.env,{userId:source.user.id,accountId:source.row.cloud_account_id,fileId:source.row.id,operation:'move',payload:{destinationVirtualPath,destinationRemoteParentId:destination?.remote_file_id||null}});const result=await performMove(c.env,account,source.row,{remoteParentId:destination?.remote_file_id||'root',virtualPath:destinationVirtualPath});remoteSucceeded=true;await updateSaga(c.env,sagaId,'remote_succeeded',{destinationVirtualPath,destinationRemoteParentId:destination?.remote_file_id||null});const oldFolderPrefix=normalizePath(`${source.row.virtual_path||'/'}${source.row.file_name}`);
      try{if(source.row.is_folder){await db`UPDATE file_metadata SET virtual_path=CASE WHEN id=${source.row.id} THEN ${destinationVirtualPath} ELSE ${destinationVirtualPath} || substring(virtual_path from ${oldFolderPrefix.length+1}) END,remote_parent_id=CASE WHEN id=${source.row.id} THEN ${destination?.remote_file_id||null} ELSE remote_parent_id END,updated_at=NOW() WHERE user_id=${source.user.id} AND cloud_account_id=${source.row.cloud_account_id} AND (id=${source.row.id} OR left(virtual_path,char_length(${oldFolderPrefix}))=${oldFolderPrefix})`;}else{await db`UPDATE file_metadata SET virtual_path=${destinationVirtualPath},remote_parent_id=${destination?.remote_file_id||null},updated_at=NOW() WHERE id=${source.row.id} AND user_id=${source.user.id} AND cloud_account_id=${source.row.cloud_account_id}`;}}catch(dbError){try{await syncStorageAccount(c.env,source.user.id,account);}catch(syncError){console.error('[files] move reconciliation sync failed:',syncError);}throw dbError;}await completeSaga(c.env,sagaId);
      return c.json({data:{success:true,file:{...result,virtualPath:destinationVirtualPath}}});
    }catch(error){if(sagaId){try{await failSaga(c.env,sagaId,error,remoteSucceeded);}catch(sagaError){console.error('[files] move saga update failed:',sagaError);}}return errorResponse(c,error,'Move failed','MOVE_FAILED');}
  });
  app.delete('/api/files/:id',async(c)=>{let sagaId=null;let remoteSucceeded=false;try{const result=await getFile(c,c.req.param('id'));await assertActive(result.row);const account=await getAccount(c,result.row.cloud_account_id);sagaId=await startSaga(c.env,{userId:result.user.id,accountId:result.row.cloud_account_id,fileId:result.row.id,operation:'delete',payload:{fileName:result.row.file_name,virtualPath:result.row.virtual_path}});let remoteAlreadyGone=false;try{await performDelete(c.env,account,result.row);}catch(deleteError){if(!isProviderAlreadyDeleted(deleteError))throw deleteError;remoteAlreadyGone=true;}remoteSucceeded=true;await updateSaga(c.env,sagaId,'remote_succeeded',{remoteAlreadyGone});await sql(c.env)`DELETE FROM file_metadata WHERE id=${result.row.id} AND user_id=${result.user.id}`;if(result.row.is_folder)await purgeVirtualFolderRows(sql(c.env),result.user.id,result.row);await completeSaga(c.env,sagaId);return c.json({data:{success:true,remoteAlreadyGone}});}catch(error){if(sagaId){try{await failSaga(c.env,sagaId,error,remoteSucceeded);}catch(sagaError){console.error('[files] delete saga update failed:',sagaError);}}return errorResponse(c,error,'Delete failed','DELETE_FAILED');}});
  app.post('/api/files/bulk/delete',async(c)=>{try{const user=await requireUser(c);const ids=[...new Set((await c.req.json()).ids||[])].filter(Boolean);if(!ids.length)return c.json({error:'At least one file id is required',code:'IDS_REQUIRED'},400);if(ids.length>100)return c.json({error:'Too many files in one request',code:'TOO_MANY_FILES'},400);const db=sql(c.env);const rows=await db`SELECT fm.*,ca.provider,ca.email,ca.encrypted_credentials,ca.status AS account_status FROM file_metadata fm JOIN cloud_accounts ca ON ca.id=fm.cloud_account_id WHERE fm.user_id=${user.id} AND fm.id=ANY(${ids})`;for(const row of rows){if(row.account_status!=='active')continue;const account={...row,id:row.cloud_account_id,user_id:user.id,email:row.email,provider:row.provider,encrypted_credentials:row.encrypted_credentials,status:row.account_status};await deleteRemoteTolerant(c.env,account,row);}await db`DELETE FROM file_metadata WHERE user_id=${user.id} AND id=ANY(${ids})`;return c.json({data:{success:true,count:rows.length}});}catch(error){return errorResponse(c,error,'Delete failed','DELETE_FAILED');}});
  app.post('/api/files/folders',async(c)=>{try{const user=await requireUser(c);const body=await c.req.json();const name=sanitizeFileName(body.name,{fallback:''});if(!name)return c.json({error:'Folder name is required',code:'INVALID_NAME'},400);const db=sql(c.env);const requestedId=body.cloud_account_id||body.cloudAccountId||null;const rows=requestedId?await db`SELECT * FROM cloud_accounts WHERE id=${requestedId} AND user_id=${user.id} AND status='active' LIMIT 1`:await db`SELECT * FROM cloud_accounts WHERE user_id=${user.id} AND status='active' ORDER BY used_space ASC LIMIT 1`;const account=rows[0];if(!account)return c.json({error:'No active storage account is connected',code:'NO_ACTIVE_ACCOUNT'},409);const virtualPath=normalizePath(body.virtual_path||body.virtualPath||'/');const folder=await performCreateFolder(c.env,account,{name,virtualPath,remoteParentId:body.remote_parent_id||body.remoteParentId});await db`INSERT INTO file_metadata(id,user_id,virtual_path,file_name,is_folder,is_starred,size,mime_type,cloud_account_id,remote_file_id,remote_parent_id) VALUES(${crypto.randomUUID()},${user.id},${virtualPath},${folder.fileName||name},TRUE,FALSE,0,'application/vnd.google-apps.folder',${account.id},${folder.remoteFileId},${folder.remoteParentId||null}) ON CONFLICT(cloud_account_id,remote_file_id) DO UPDATE SET file_name=EXCLUDED.file_name,virtual_path=EXCLUDED.virtual_path,updated_at=NOW()`;return c.json({data:{success:true,file:folder}},201);}catch(error){return errorResponse(c,error,'Folder creation failed','FOLDER_CREATE_FAILED');}});
  async function download(c,inline){const result=await getFile(c,c.req.param('id'));await assertActive(result.row);if(result.row.is_folder)throw Object.assign(new Error('Folders cannot be downloaded'),{status:400,code:'FOLDER_DOWNLOAD_UNSUPPORTED'});const account=await getAccount(c,result.row.cloud_account_id);const mime=inferMimeType(result.row.file_name,result.row.mime_type);const allowInline=inline&&SAFE_INLINE_MIME_TYPES.has(mime);const response=await performDownload(c.env,account,result.row);const headers=new Headers(response.headers);headers.set('Content-Disposition',`${allowInline?'inline':'attachment'}; filename="${safeDownloadFilename(result.row.file_name)}"`);if(allowInline)headers.set('Content-Type',mime);else if(!headers.get('Content-Type')||headers.get('Content-Type')==='application/octet-stream')headers.set('Content-Type','application/octet-stream');headers.set('X-Content-Type-Options','nosniff');headers.set('Cache-Control','private, no-store');return new Response(response.body,{status:response.status,headers});}
  app.get('/api/files/:id/download',async(c)=>{try{return await download(c,false);}catch(error){return errorResponse(c,error,'Download failed','DOWNLOAD_FAILED');}});
  app.get('/api/files/:id/preview',async(c)=>{try{return await download(c,true);}catch(error){return errorResponse(c,error,'Preview failed','PREVIEW_FAILED');}});
  app.post('/api/sync/run',async(c)=>{try{const user=await requireUser(c);const db=sql(c.env);const accounts=await db`SELECT * FROM cloud_accounts WHERE user_id=${user.id} AND status='active'`;const results=[];for(const account of accounts){try{results.push({accountId:account.id,provider:account.provider,...(await syncStorageAccount(c.env,user.id,account))});}catch(error){console.error('[files] sync account failed:',error);results.push({accountId:account.id,provider:account.provider,error:'Sync failed',code:'SYNC_FAILED'});}}return c.json({data:{success:true,results}});}catch(error){return errorResponse(c,error,'Sync failed','SYNC_FAILED');}});
}
